### ISSUE TITLE
Re-Running All Models for 400 Random Samples

### ISSUE THREAD

**Issue by singh96aman** [UMass-Meta-LLM-Eval/llm_eval#64]

**Comment by kartik727** [comment]
- [x] Benchmark
- [x] Automated eval
- [ ] Human eval

**Comment by singh96aman** [comment]
Can you please share the config so that we can do Human Eval ?
While doing human eval, Let's do human eval with unique error code this time. It'll help us with our analysis. Thoughts?

**Comment by kartik727** [comment]
Added the configs (see #75). Forcing single error code does not make sense since there is the possibility of having multiple errors in a response.
